import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { renderToBuffer } from '@react-pdf/renderer';
import prisma from '@/lib/prisma';

// ── Minimal PDF Styles ──────────────────────────────────────────────────────────
const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  header: { fontSize: 18, fontWeight: 'bold', marginBottom: 8, textAlign: 'center' },
  subheader: { fontSize: 12, color: '#555', marginBottom: 20, textAlign: 'center' },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 13, fontWeight: 'bold', marginBottom: 6, borderBottom: '1px solid #ccc', paddingBottom: 4 },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3 },
  label: { color: '#555' },
  value: { fontWeight: 'medium' },
  total: { fontSize: 14, fontWeight: 'bold', marginTop: 8, borderTop: '1px solid #000', paddingTop: 6 },
  footer: { fontSize: 9, color: '#999', textAlign: 'center', marginTop: 30 },
});

// ── Statement Component ────────────────────────────────────────────────────────────
interface StatementProps {
  customer: { name: string; phone: string; balance: number };
  orders: { id: string; product: string; quantity: number; total: number; status: string; createdAt: string }[];
  transactions: { type: string; amount: number; balanceAfter: number; createdAt: string }[];
  period: string;
}

function Statement({ customer, orders, transactions, period }: StatementProps) {
  const totalOrders = orders.reduce((s, o) => s + Number(o.total), 0);
  const totalPayments = transactions
    .filter((t) => t.type === 'PAYMENT')
    .reduce((s, t) => s + Number(t.amount), 0);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>🐔 Customer Statement</Text>
        <Text style={styles.subheader}>{period}</Text>

        {/* Customer Info */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Customer</Text>
          <View style={styles.row}><Text style={styles.label}>Name:</Text><Text style={styles.value}>{customer.name}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Phone:</Text><Text style={styles.value}>{customer.phone}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Balance:</Text><Text style={styles.value}>₦{Number(customer.balance).toFixed(2)}</Text></View>
        </View>

        {/* Orders */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Orders ({orders.length})</Text>
          {orders.map((o, i) => (
            <View key={i} style={styles.row}>
              <Text style={styles.label}>{o.product} × {o.quantity}kg</Text>
              <Text style={styles.value}>₦{Number(o.total).toFixed(2)} ({o.status})</Text>
            </View>
          ))}
          <Text style={styles.total}>Orders Total: ₦{totalOrders.toFixed(2)}</Text>
        </View>

        {/* Transactions */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Transactions ({transactions.length})</Text>
          {transactions.map((t, i) => (
            <View key={i} style={styles.row}>
              <Text style={styles.label}>{t.type} — {new Date(t.createdAt).toLocaleDateString()}</Text>
              <Text style={styles.value}>₦{Number(t.amount).toFixed(2)} → Bal: ₦{Number(t.balanceAfter).toFixed(2)}</Text>
            </View>
          ))}
          <Text style={styles.total}>Payments Received: ₦{totalPayments.toFixed(2)}</Text>
        </View>

        <Text style={styles.footer}>Generated by Church Chicken Sales — {new Date().toLocaleDateString()}</Text>
      </Page>
    </Document>
  );
}

// ── Generate PDF Buffer ───────────────────────────────────────────────────────────
export async function generateStatementPDF(
  customerId: string,
  startDate: Date,
  endDate: Date
): Promise<Buffer> {
  const customer = await prisma.customer.findUnique({
    where: { id: customerId },
    select: { name: true, phone: true, balance: true },
  });
  if (!customer) throw new Error('Customer not found');

  const orders = await prisma.order.findMany({
    where: {
      customerId,
      createdAt: { gte: startDate, lte: endDate },
    },
    include: { product: { select: { name: true } } },
    orderBy: { createdAt: 'asc' },
  });

  const transactions = await prisma.transaction.findMany({
    where: {
      customerId,
      createdAt: { gte: startDate, lte: endDate },
    },
    orderBy: { createdAt: 'asc' },
  });

  const period = `${startDate.toLocaleDateString()} – ${endDate.toLocaleDateString()}`;

  const pdfBuffer = await renderToBuffer(
    Statement({
      customer: {
        name: customer.name,
        phone: customer.phone,
        balance: Number(customer.balance),
      },
      orders: orders.map((o) => ({
        id: o.id,
        product: o.product.name,
        quantity: o.quantity,
        total: Number(o.total),
        status: o.status,
        createdAt: o.createdAt.toISOString(),
      })),
      transactions: transactions.map((t) => ({
        type: t.type,
        amount: Number(t.amount),
        balanceAfter: Number(t.balanceAfter),
        createdAt: t.createdAt.toISOString(),
      })),
      period,
    })
  );

  return Buffer.from(pdfBuffer);
}

// ── Invoice PDF ────────────────────────────────────────────────────────────────────
interface InvoiceItemPDF {
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
  cost: number;
}

interface InvoicePDFProps {
  number: string;
  customer: { name: string; phone: string };
  issueDate: string;
  dueDate: string | null;
  items: InvoiceItemPDF[];
  subtotal: number;
  tax: number;
  total: number;
  totalCost: number;
  status: string;
  notes: string | null;
}

const invoiceStyles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  brand: { fontSize: 20, fontWeight: 'bold' },
  invoiceTitle: { fontSize: 16, fontWeight: 'bold', color: '#444' },
  meta: { fontSize: 10, color: '#555', marginTop: 4 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 6, borderBottom: '1px solid #ccc', paddingBottom: 4 },
  row: { flexDirection: 'row', paddingVertical: 4 },
  colDesc: { flex: 5 },
  colQty: { flex: 2, textAlign: 'right' },
  colPrice: { flex: 2, textAlign: 'right' },
  colAmount: { flex: 3, textAlign: 'right' },
  tableHead: { fontSize: 10, fontWeight: 'bold', color: '#555', borderBottom: '1px solid #000' },
  totalsRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3 },
  total: { fontSize: 14, fontWeight: 'bold', marginTop: 6, borderTop: '2px solid #000', paddingTop: 6 },
  footer: { fontSize: 9, color: '#999', textAlign: 'center', marginTop: 30 },
});

function InvoicePDF({ number, customer, issueDate, dueDate, items, subtotal, tax, total, totalCost, status, notes }: InvoicePDFProps) {
  const profit = total - totalCost;
  const showProfit = totalCost > 0;
  return (
    <Document>
      <Page size="A4" style={invoiceStyles.page}>
        <View style={invoiceStyles.headerRow}>
          <View>
            <Text style={invoiceStyles.brand}>🐔 Church Chicken Sales</Text>
            <Text style={invoiceStyles.meta}>Farm & Poultry Supplies</Text>
          </View>
          <View>
            <Text style={invoiceStyles.invoiceTitle}>INVOICE</Text>
            <Text style={invoiceStyles.meta}>{number}</Text>
            <Text style={invoiceStyles.meta}>Status: {status}</Text>
          </View>
        </View>

        <View style={invoiceStyles.section}>
          <Text style={invoiceStyles.sectionTitle}>Bill To</Text>
          <Text>{customer.name}</Text>
          <Text style={invoiceStyles.meta}>{customer.phone}</Text>
        </View>

        <View style={invoiceStyles.section}>
          <Text style={invoiceStyles.sectionTitle}>Invoice Details</Text>
          <View style={invoiceStyles.totalsRow}>
            <Text style={invoiceStyles.meta}>Issue Date:</Text>
            <Text>{new Date(issueDate).toLocaleDateString()}</Text>
          </View>
          <View style={invoiceStyles.totalsRow}>
            <Text style={invoiceStyles.meta}>Due Date:</Text>
            <Text>{dueDate ? new Date(dueDate).toLocaleDateString() : '—'}</Text>
          </View>
        </View>

        <View style={invoiceStyles.section}>
          <Text style={invoiceStyles.sectionTitle}>Items</Text>
          <View style={[invoiceStyles.row, invoiceStyles.tableHead]}>
            <Text style={invoiceStyles.colDesc}>Description</Text>
            <Text style={invoiceStyles.colQty}>Qty</Text>
            <Text style={invoiceStyles.colPrice}>Price</Text>
            <Text style={invoiceStyles.colPrice}>Cost</Text>
            <Text style={invoiceStyles.colAmount}>Amount</Text>
          </View>
          {items.map((it, i) => (
            <View key={i} style={invoiceStyles.row}>
              <Text style={invoiceStyles.colDesc}>{it.description}</Text>
              <Text style={invoiceStyles.colQty}>{it.quantity}</Text>
              <Text style={invoiceStyles.colPrice}>₦{it.unitPrice.toFixed(2)}</Text>
              <Text style={invoiceStyles.colPrice}>₦{it.cost.toFixed(2)}</Text>
              <Text style={invoiceStyles.colAmount}>₦{it.amount.toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <View style={invoiceStyles.section}>
          <View style={invoiceStyles.totalsRow}>
            <Text style={invoiceStyles.meta}>Subtotal:</Text>
            <Text>₦{subtotal.toFixed(2)}</Text>
          </View>
          <View style={invoiceStyles.totalsRow}>
            <Text style={invoiceStyles.meta}>Tax:</Text>
            <Text>₦{tax.toFixed(2)}</Text>
          </View>
          <View style={invoiceStyles.total}>
            <Text>Total Due: ₦{total.toFixed(2)}</Text>
          </View>
          {showProfit ? (
            <View style={[invoiceStyles.totalsRow, { marginTop: 8, paddingTop: 6, borderTop: '1px solid #ccc' }]}>
              <Text style={[invoiceStyles.meta, { fontWeight: 'bold' }]}>
                {profit >= 0 ? '📈 Profit' : '📉 Loss'}:
              </Text>
              <Text style={{ fontWeight: 'bold', color: profit >= 0 ? '#16a34a' : '#dc2626' }}>
                ₦{Math.abs(profit).toFixed(2)}
              </Text>
            </View>
          ) : null}
        </View>

        {notes ? (
          <View style={invoiceStyles.section}>
            <Text style={invoiceStyles.sectionTitle}>Notes</Text>
            <Text style={invoiceStyles.meta}>{notes}</Text>
          </View>
        ) : null}

        <Text style={invoiceStyles.footer}>Thank you for your business — Generated {new Date().toLocaleDateString()}</Text>
      </Page>
    </Document>
  );
}

export async function generateInvoicePDF(invoiceId: string): Promise<Buffer> {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      customer: { select: { name: true, phone: true } },
      items: true,
    },
  });
  if (!invoice) throw new Error('Invoice not found');

  const pdfBuffer = await renderToBuffer(
    InvoicePDF({
      number: invoice.number,
      customer: invoice.customer,
      issueDate: invoice.issueDate.toISOString(),
      dueDate: invoice.dueDate ? invoice.dueDate.toISOString() : null,
      items: invoice.items.map((it) => ({
        description: it.description,
        quantity: Number(it.quantity),
        unitPrice: Number(it.unitPrice),
        amount: Number(it.amount),
        cost: Number(it.cost),
      })),
      subtotal: Number(invoice.subtotal),
      tax: Number(invoice.tax),
      total: Number(invoice.total),
      totalCost: invoice.items.reduce((s, it) => s + Number(it.cost), 0),
      status: invoice.status,
      notes: invoice.notes,
    })
  );

  return Buffer.from(pdfBuffer);
}